version: '3.8'

services:
  neurotech-client-database:
    image: mysql:5.7
    container_name: neurotech-client-database
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$MYSQLDB_ROOT_PASSWORD
    networks:
      neurotech-network:
    volumes:
      - db:/var/lib/mysql
  neurotech-client-service:
    container_name: neurotech-client-service
    depends_on:
      neurotech-client-database:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - "5000:5000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://neurotech-client-database:3306/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=$SPRING_DB_USER_NAME
      - SPRING_DATASOURCE_PASSWORD=$SPRING_DB_USER_PASSWORD
    networks:
      neurotech-network:

networks:
  neurotech-network:

volumes:
  db: